name: Check DESCRIPTION File

on:
  pull_request:
    types: [opened, synchronize]

permissions: {}

jobs:
  check-description-file:
    if: ${{ github.event.pull_request.head.repo.fork == true }} # Only run on PRs from forks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # Step 2: Check if the DESCRIPTION file exists
      - name: Verify DESCRIPTION file exists
        run: |
          if [ ! -f "DESCRIPTION" ]; then
            echo "ERROR: DESCRIPTION file is missing."
            exit 1
          else
            echo "DESCRIPTION file exists."
          fi

      - name: Check for package name in DESCRIPTION
        run: |
          PACKAGE_NAME=$(cat DESCRIPTION | grep "^Package:" | awk '{print $2}')
          if [ -z "$PACKAGE_NAME" ]; then
            echo "Error: Package name not found in DESCRIPTION" >&2
            exit 1
          fi
          # Prevent special characters in package name
          if [[ ! "$PACKAGE_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
            echo "Error: PACKAGE_NAME contains invalid characters!" >&2
            exit 1
          fi
        shell: bash

      - name: Check if `.github/` folder was modified using Git diff
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

          echo "Changed files:"
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "^\.github/"; then
            echo "❌ The `modules/` folder was been modified."
            exit 1
          else
            echo "✅ The `modules/` folder has NOT modified."
          fi
