on:
  workflow_dispatch:

# once the module takes shape you may want to uncomment these lines
#on:
#  push:
#    paths: ['**.R', 'tests/**', '**.Rd', '**.c', '**.cpp', '**.h', '**.hpp', 'DESCRIPTION', 'NAMESPACE', 'MAKEVARS', 'MAKEVARS.win', '**.yml']
#  pull_request:
#    paths: ['**.R', 'tests/**', '**.Rd', '**.c', '**.cpp', '**.h', '**.hpp', 'DESCRIPTION', 'NAMESPACE', 'MAKEVARS', 'MAKEVARS.win']
#  schedule:
#    - cron:  '13 12 * * 1-5'

name: unit-tests

jobs:

  unit-tests:
    # this ensures the action is not run twice when creating a pull request from within the same repository
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: jasp-stats/jasp-actions/.github/workflows/unittests.yml@v1
    with:
      needs_JAGS:   false
